name: Cross Jobs Example

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      job1_output: ${{ steps.set-output.outputs.my_output }}
    steps:
      - name: Set output variable
        id: set-output
        run: |-
          echo "::set-output name=my_output::Secret from Job 1: ${{ secrets.ENV_SECRET }}"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Use job1 output
        run: echo "${{ needs.job1.outputs.job1_output }}"
