name: Cross Jobs Example

on: [push]

jobs:
  environment-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        run: echo "MY_VARIABLE=Hello From environment-step" >> $GITHUB_ENV
      
      - name: Use environment variable
        run: echo $MY_VARIABLE

  output-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set output variable
        id: step1
        run: |-
          echo "my_output=Hello from output-step" >> $GITHUB_OUTPUT
      
      - name: Use output variable
        run: echo "${{ steps.step1.outputs.my_output }}"
