name: Cross Jobs Example

on: [push]

jobs:
  upload-job:
    name: Pass values by artifacts
    runs-on: ubuntu-latest
    steps:
    - name: Create artifact
      run: echo "artifact_content" > artifact.txt
      # Upload artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: my-artifact
          path: artifact.txt

  download-job:
    name: Get values by artifacts
    needs: upload-job
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: Use artifact
        run: cat artifact.txt
    
  output-job:
        name: Pass values by needs
        runs-on: ubuntu-latest
        outputs:
          job_output: ${{ steps.set-output.outputs.my_output }}
        steps:
        - name: Set output variable
          id: set-output
          run: |-
            echo "my_output=Hello from output-job" >> $GITHUB_OUTPUT
  get-job:
        name: Get values by needs
        runs-on: ubuntu-latest
        needs: output-job
        steps:
        - name: Use output-job output
          run: |-
            echo "${{ needs.output-job.outputs.job_output }}"
