name: CI/CD Pipeline

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: [self-hosted, test-runner]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm run test
  
  deploy-to-dev:
    runs-on: [self-hosted, test-runner]
    needs: build
    env:
      ENV_SECRET: ${{ secrets.ENV_SECRET }}
      PROD_SECRET: ${{ secrets.PROD_SECRET }}
    steps:
    - name: Deploy to Development

      run: |
        echo "Deploying to development environment..."
        ./deploy-dev.sh '${{ env.ENV_SECRET }}' '${{ env.PROD_SECRET }}'

  deploy-to-prod:
    needs: deploy-to-dev
    runs-on: [self-hosted, test-runner]
    environment: 
      name: production
    env:
      ENV_SECRET: ${{ secrets.ENV_SECRET }}
      PROD_SECRET: ${{ secrets.PROD_SECRET }}
    steps:
    - name: Deploy to Production Environment
      run: |
        echo "Deploying to production environment..."
        ./deploy-prod.sh '${{ env.ENV_SECRET }}' '${{ env.ENV_SECRET }}'
