name: Workflow 2

on:
  repository_dispatch:
    types: [trigger-workflow-2]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Receive payload
        run: echo "Received message: ${{ github.event.client_payload.message }}"
